Added range parameters to the list_twins
Iotic-Labs/iotics-grpc-client-py pull request #45
Opened 2024-06-30 22:30 UTC by ipeteclarke

Added range parameters to the list_twins to allow paging through results. 

I have try to make the behavior consistent with search.dispatch_request functions which also uses the range parameter.
To make this more readable, I moved the PER_PAGE_LIMIT to the helpers class.

There is also an update to the Makefile I needed to make this work ootb with ubuntu 22.04 (python command not in place by default).  

The example will page through the local twin list until it has received all the twins (identified by not having a full page)

Example output is 

```
(env) ➜  iotics-grpc-client-py git:(main) ✗ python3 examples/list_local_twins.py

Got replies from page #0 and found 100 twins on this page.
Got replies from page #1 and found 8 twins on this page.
found 108 twins in total.
```

2024-07-02 07:58 UTC, conbon commented on src/iotics/lib/grpc/twins.py
> +from .helpers import create_headers,PER_PAGE_LIMIT
pedantic: consistent spacing with the other example file

2024-07-02 07:58 UTC, conbon commented on src/iotics/lib/grpc/twins.py
> +                   page:int =0,
same here `page:int = 0`

2024-07-02 08:00 UTC, conbon commented on src/iotics/lib/grpc/twins.py
> +            page: Used to request offsetted results, as responses contain only up to `PER_PAGE_LIMIT` results per request.
just `offset results` ?

2024-07-02 08:04 UTC, conbon commented on examples/list_local_twins.py
> +    client_app_id = uuid.uuid4().hex
These are unused - can remove. 
Can also remove the commented `print (twin_list)`

2024-07-02 08:08 UTC, conbon requested changes
I'm seeing changes in the protobuf generation locally for some reason. 
We were seeing issues with it before but could pin down why it was happening.

One of the other example runner Github Actions is also failing - I'm wondering if it's because you have created a PR from your own main branch instead of a branch in this repo. When it runs the injected secrets look blank. 

We might need to cherry-pick these and open a new PR maybe

2024-07-02 08:41 UTC, captnz reviewed
Works for me! 
We'll pull it in next week when we have some more time.

Just made some comments which we'll fix when we pull it in if the comments look ok with you?

Running a search, or a sparql query might have got you what you needed without the changes, dont know?

2024-07-03 20:01 UTC, ipeteclarke commented on src/iotics/lib/grpc/twins.py
> +            page: Used to request offsetted results, as responses contain only up to `PER_PAGE_LIMIT` results per request.
Took this text from the search API so that it is consitent

2024-07-03 20:09 UTC, ipeteclarke commented
changes checked in based on comments

2024-07-14 21:32 UTC, ipeteclarke commented
@captnz @conbon  Would you have some time to look at merge and release?

2024-07-15 11:25 UTC, conbon commented
Merged in https://github.com/Iotic-Labs/iotics-grpc-client-py/pull/47

2024-07-15 11:25 UTC, closed without merging